INSERT INTO permissions (code, description)
VALUES
  ('dashboard.read', 'Ver dashboard'),
  ('products.read', 'Ver produtos'),
  ('products.write', 'Criar/editar produtos'),
  ('content.read', 'Ver conteúdos (módulos/aulas)'),
  ('content.write', 'Criar/editar conteúdos'),
  ('media.read', 'Ver biblioteca de mídia'),
  ('media.write', 'Gerenciar vídeos e arquivos'),
  ('member_areas.read', 'Ver áreas de membros'),
  ('member_areas.write', 'Criar/editar áreas de membros'),
  ('community.read', 'Ver comunidade'),
  ('community.write', 'Criar postagens/comentários'),
  ('community.moderate', 'Moderar comunidade'),
  ('members.read', 'Ver membros'),
  ('members.write', 'Criar/editar membros'),
  ('access_groups.read', 'Ver grupos de acesso'),
  ('access_groups.write', 'Criar/editar grupos de acesso'),
  ('cohorts.read', 'Ver turmas'),
  ('cohorts.write', 'Criar/editar turmas'),
  ('enrollments.read', 'Ver matrículas'),
  ('enrollments.write', 'Criar/cancelar matrículas'),
  ('progress.read', 'Ver progresso dos alunos'),
  ('reports.read', 'Ver relatórios'),
  ('reports.export', 'Exportar relatórios'),
  ('pay.read', 'Ver financeiro'),
  ('pay.refund', 'Executar reembolsos'),
  ('pay.payouts', 'Gerenciar repasses'),
  ('gamification.read', 'Ver gamificação'),
  ('gamification.write', 'Configurar gamificação'),
  ('comms.read', 'Ver comunicação'),
  ('comms.write', 'Criar campanhas e templates'),
  ('integrations.read', 'Ver integrações'),
  ('integrations.write', 'Configurar integrações'),
  ('webhooks.read', 'Ver webhooks'),
  ('webhooks.write', 'Criar/editar webhooks'),
  ('ai.read', 'Ver agentes IA'),
  ('ai.write', 'Configurar agentes IA'),
  ('settings.read', 'Ver configurações do tenant'),
  ('settings.write', 'Editar configurações do tenant'),
  ('users.invite', 'Convidar usuários'),
  ('users.roles', 'Gerenciar papéis e permissões')
ON CONFLICT (code) DO NOTHING;
